- name: app-setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup
- name: java
  ansible.builtin.import_role:
   name: common
   tasks_from: java
- name: mysql
  ansible.builtin.import_role:
   name: common
   tasks_from: mysql-setup
- name: systemdb
  ansible.builtin.import_role:
   name: common
   tasks_from: systemdb