- name: "stop {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
   name: "{{component}}"
   state: stopped

- name: remove app directory
  tags:
  - deployment
  ansible.builtin.file:
   path: "/app*"
   state: absent
  